export const SETCURRENTTRACK = "SETCURRECTTRACK";
export const SETPLAYING = "SETPLAYING";
export const SETTRACKLIST = "SETTRACKLIST";
export const CURRENTINDEX = "CURRENTINDEX";
export const RESET = "RESET";
export const NEXTTRACK = "NEXTTRACK";
export const PREVTRACK = "PREVTRACK";
export const PLAYTRACK = "PLAYTRACK";